# Configuración del Microservicio
spring.application.name=ms-auth
server.port=8087

# Base de Datos (ms-auth suele compartir la DB con ms-user o tener la propia)
# Asegúrate de que la base de datos exista o usa ?createDatabaseIfNotExist=true
spring.datasource.url=jdbc:mysql://localhost:3306/ms_auth?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=purogol2026

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Flyway (Si vas a manejar migraciones de tablas de tokens o usuarios)
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Seguridad JWT
# ¡IMPORTANTE! Esta clave debe ser EXACTAMENTE la misma en todos los microservicios
jwt.secret=esta_es_una_clave_secreta_muy_larga_y_segura_1234567890

# Configuración de Logs (IE 2.3.2)
logging.level.root=INFO
logging.level.com.marketplace.ms_auth=DEBUG
logging.level.org.hibernate.SQL=DEBUG