# 1. Servidor
server.port=8082
spring.application.name=ms-catalog

# 2. Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/ms_catalog?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=purogol2026

# 3. Hibernate y JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# 4. Flyway (Para crear tablas y datos de prueba)
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# 5. Jackson
spring.jackson.serialization.write-dates-as-timestamps=false

jwt.secret= "esta_es_una_clave_secreta_muy_larga_y_segura_1234567890";