spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ms_catalog}?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
eureka:
  instance:
    prefer-ip-address: true
logging:
  level:
    root: INFO
    org.springframework.security: WARN

services:
  inventory:
    url: ${SERVICES_INVENTORY_URL:http://ms-inventory:8084/api/v1/inventory}
  search:
    url: ${SERVICES_SEARCH_URL:http://ms-search:8089/api/search}
