
# 1. Configuración del Servidor
server.port=8080
spring.application.name=ms-user

# 2. Configuración de la Base de Datos (userdb)
# Asegúrate de haber ejecutado: CREATE DATABASE userdb; en tu MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=purogol2026

# 3. Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 4. Configuración de Flyway (Para las migraciones SQL)
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# 5. Formato de JSON (Opcional, para que las fechas se vean bien)
spring.jackson.serialization.write-dates-as-timestamps=false

# 6. Logging (Para ver errores detallados en consola)
logging.level.org.springframework.security=DEBUG