spring.application.name=ms-payment
# 1. Configuración del Servidor
server.port=8088
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# 2. Configuración de la Base de Datos (ms_payment)
# He cambiado el nombre a ms_payment para que sea consistente con tus otros micros
spring.datasource.url=jdbc:mysql://localhost:3306/ms_payment?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:}

# 3. Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 4. Configuración de Flyway (deshabilitado: migración V1 falló previamente en BD local)
spring.flyway.enabled=false

# 5. CONFIGURACIÓN DE LOGS (Lo que necesitabas)
# Esto crea la carpeta /logs y el archivo dentro de la raíz del proyecto
logging.file.name=logs/ms-payment.log
# Define qué tanto detalle quieres guardar en el archivo
logging.level.root=INFO
logging.level.com.marketplace=DEBUG
logging.level.org.springframework.security=DEBUG
# Formato de la fecha en los logs


# 6. Seguridad JWT (Asegúrate de que sea la misma clave que ms-user)
jwt.secret=esta_es_una_clave_secreta_muy_larga_y_segura_1234567890