eureka:
  instance:
    prefer-ip-address: true

services:
  catalog:
    url: ${SERVICES_CATALOG_URL:http://ms-catalog:8085/api/v1/catalog}
  inventory:
    url: ${SERVICES_INVENTORY_URL:http://ms-inventory:8084/api/v1/inventory}

logging:
  level:
    root: INFO
    com.marketplace.product_service: INFO
