spring.application.name=ms-producto
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
server.port=${SERVER_PORT:8082}

eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

services.catalog.url=${SERVICES_CATALOG_URL:http://localhost:8085/api/catalog}
services.inventory.url=${SERVICES_INVENTORY_URL:http://localhost:8084/api/inventory}

jwt.secret=${JWT_SECRET:esta_es_una_clave_secreta_muy_larga_y_segura_1234567890}
