spring.application.name=ms-producto
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Sin base de datos local: ms-producto orquesta catalog + inventory
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

services.catalog.url=http://localhost:8085/api/v1/catalog
services.inventory.url=http://localhost:8084/api/v1/inventory

jwt.secret=esta_es_una_clave_secreta_muy_larga_y_segura_1234567890

logging.level.root=INFO
logging.level.com.marketplace.product_service=DEBUG
