
# 1. Configuración del Servidor
server.port=8084
spring.application.name=ms-inventory

# 2. Configuración de la Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/ms_inventory?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=purogol2026

# 3. Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 4. Configuración de Flyway (Pónlo en false si aún no tienes los scripts .sql)
spring.flyway.enabled=false 

# 5. Formato de JSON
spring.jackson.serialization.write-dates-as-timestamps=false

# 6. Logging
logging.level.org.springframework.security=DEBUG